### ISSUE TITLE
SNMP package have to installed to run Scheduler

### ISSUE THREAD

**Issue by anhtuank7c** [trentrichardson/cakephp-scheduler#12]
Dear @trentrichardson 

My your Scheduler have to install snmp package to run Scheduler.

You did not mention this package.

My server do not install `snmp`, i try run: bin/cake Scheduler.Scheduler to run, but i always get error: `Cannot find module (SNMPv2-MIB) ...`

I think you must update your document.

**Comment by trentrichardson** [comment]
Hey @anhtuank7c 
This plugin has no dependencies outside of CakePHP.  

Does one of the tasks you are running may require that library?

**Comment by anhtuank7c** [comment]
No, it doesn't.

My Task just use ConnectionManager, and Log class.

No thing more.

Here my Task class: [Here](https://gist.github.com/anhtuank7c/a4becbf5db9932542410)

**Comment by anhtuank7c** [comment]
I this plugin make cronjob simple, but i have to type: `bin/cake Scheduler.Scheduler` to run Shell, if not, the Shell do not run.

To make Shell always run in all case, do i have to create cronjob to call your Scheduler every minute right?

**Comment by anhtuank7c** [comment]
Seem right. :)
