### ISSUE TITLE
Example 15min task in readme runs every 15months

### ISSUE THREAD

**Issue by half2me** [trentrichardson/cakephp-scheduler#15]
According to https://secure.php.net/manual/en/class.dateinterval.php
A 15minute task should be: 'PT15I' (Readme incorrectly says: 'PT15M')

y
Number of years.

m
Number of months.

d
Number of days.

h
Number of hours.

i
Number of minutes.

s
Number of seconds.

**Comment by anhtuank7c** [comment]
M = Minute.
Please read more about `DateInterval __construct()` here: http://php.net/manual/en/dateinterval.construct.php

You can see image bellow, after create `$tim = new DateInterval('PT10M');`
![schedule](https://cloud.githubusercontent.com/assets/3163410/12216698/1e3f4702-b72e-11e5-88d1-70e64c545f34.PNG)

**Comment by half2me** [comment]
@anhtuank7c I see.

**Comment by half2me** [comment]
Well using PT5M for me just runs it once and thats it...

**Comment by anhtuank7c** [comment]
Examples:

```
PT1S = each second
PT1M = each minute
PT1H = each hour
P1D = each day
P1W = each week
P1M = each month
P1Y = each year
```

@half2me  How it's going?

I think we can close this issue.
