### ISSUE TITLE
Default action is main() not execute()

### ISSUE THREAD

**Issue by half2me** [trentrichardson/cakephp-scheduler#17]
The readme.md says that the default action if left empty will be execute()
but in the [code:](https://github.com/trentrichardson/cakephp-scheduler/blob/3.0.2/src/Shell/SchedulerShell.php#L103) we have `$v = $v + array('action' => 'main', 'pass' => array());`
And that is being passed to line 124: `public function connect($name, $interval, $task, $action = 'execute', $pass = array()) {`

So although it defaults to execute... it still actually defaults to main. Which I think is the preferred behavior. So line 103 is redundant, and the `+ array` part can be removed

**Comment by trentrichardson** [comment]
Ok, I have fixed this in the cakephp-v3.0 branch.  I would like to get your other pull (https://github.com/trentrichardson/cakephp-scheduler/issues/18) done, then try to merge a new version to the master branch.
