### ISSUE TITLE
scheduler Can not find task class

### ISSUE THREAD

**Issue by CaioSchmtt** [trentrichardson/cakephp-scheduler#22]
I can execute my tasks manually, but when I use the scheduler it does not find the job I configured:
\ / Bootstrap_cli
```
Configure :: write ('SchedulerShell.jobs', array (
    'UpdateTrackingByOrders' => array ('interval' => 'PT2M', 'task' => 'UpdateTrackingByOrders') // every 2 minutes
));
```

Console display on execute cake Scheduler.Scheduler

```
Exception: Task class UpdateTrackingByOrders could not be found. In [C: \ xampp \ htdocs \ MLFacil \ vendor \ cakephp \ cakephp \ src \ Console \ TaskRegistry.php, line 70]
2017-08-02 17:20:10 Error: [Cake \ Console \ Exception \ MissingTaskException] Task class UpdateTrackingByOrders could not be found. In C: \ xampp \ htdocs \ MLFacil \ vendor \ cakephp \ cakephp \ src \ Console \ TaskRegistry.php on line 70
Exception Attributes: array (
  'Class' => 'UpdateTrackingByOrders',
  'Plugin' => NULL,
)
```

The right folder to place the jobs is not in app/src/Shell/UpdateTrackingByOrdersShell.php ? 
please help me

**Comment by half2me** [comment]
@CaioSchmtt almost :) Try using `app/src/Shell/Task/UpdateTrackingByOrdersTask.php`
make sure you use the namespace: `App\Shell\Task`
Everything else behaves like a normal Shell.

**Comment by CaioSchmtt** [comment]
Thank you, I was never going to find out kkk

**Comment by half2me** [comment]
@CaioSchmtt no problem :) glad to help
