### ISSUE TITLE
Storage of Results not Working

### ISSUE THREAD

**Issue by CaioSchmtt** [trentrichardson/cakephp-scheduler#23]
Good morning, in the documentation says that by default is created the file scheduler_results.json ..
But he is not recording ..
Has another file called .scheduler_running_flag .. but this json is not being created ..

What can it be?
Thank you!

**Comment by trentrichardson** [comment]
First I would check that the job was not erroring out. It firsts creates the flag file, then runs the jobs, then it writes the results of that file after the jobs run and deletes the flag file. Sounds like it doesn't complete the jobs and ends before it writes the files. Make sure those jobs did not error out. You may try running it manually from the terminal to do that or check your logs.
