### ISSUE TITLE
Rename repository as suggested by Cookbook

### ISSUE THREAD

**Issue by houseoftech** [trentrichardson/cakephp-scheduler#8]
The [Cookbook article on creating plugins](http://book.cakephp.org/2.0/en/plugins/how-to-create-plugins.html#publish-your-plugin) recommends a naming convention for a plugin.

i.e. cakephp-scheduler

**Comment by trentrichardson** [comment]
I'm ok with renaming.  I also want to get this setup for composer.  I also will be getting into cakephp 3 soon and need to begin preparing for that soon as well.  Have you worked with 3 yet and know of any major changes that would need to take place?  I appreciate your contributions so far!

**Comment by houseoftech** [comment]
A composer setup would be great. Will you also submit to Packagist?

I haven't looked into 3.0 yet except for the better integration with composer. You can run the Migration plugin to see what it brings up.

**Comment by trentrichardson** [comment]
I can try to get it renamed tonight.  Then look at composer and submit it to Packagist.

**Comment by houseoftech** [comment]
Here's a starter for your composer.json:

```
{
    "name": "trentrichardson/cakephp-scheduler",
    "type": "cakephp-plugin",
    "description": "Makes scheduling tasks in CakePHP much simpler.",
    "keywords": ["cakephp","scheduler","cron job","task"],
    "homepage": "http://github.com/trentrichardson/cakephp-scheduler",
    "require": {
        "php": ">=5.3.6",
        "composer/installers": "*"
    },
    "support": {
        "source": "https://github.com/trentrichardson/cakephp-scheduler"
    },
    "extra": {
        "installer-name": "Scheduler"
    }
}
```

**Comment by trentrichardson** [comment]
Ok, I have added the composer.json, tagged a release, and submitted to packagist, and added an auto update hook from github to packagist.  Now just need to test out if everything works properly. @houseoftech 

https://packagist.org/packages/trentrichardson/cakephp-scheduler

**Comment by houseoftech** [comment]
I tested in my project and it works well. Thank you @trentrichardson

**Comment by trentrichardson** [comment]
@houseoftech I wanted to give you a heads up.  I have updated the repo (and packagist) to where the master branch is for cake 3.  I tagged the cake 2 version as 2.0.0 as a release and created a separate branch cakephp-v2.0 if you need to reference that for live updates. 

Note: There is a 1.0.0 tag but it is the same as 2.0.0, I just wanted to sync the version with cake major versions, so tag 1.0.0 does _not_ refer to cakephp 1 (there is a branch cakephp-v1.0 for that).

**Comment by houseoftech** [comment]
Thanks. I'll update my 1.0.0 references to 2.0.0.
